DROP TABLE IF EXISTS Posts;
CREATE TABLE Posts(
    PostID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PostTitle VARCHAR(20) NOT NULL,
    Username VARCHAR(15) NOT NULL,
    PostContent VARCHAR(250) NOT NULL,
    DatePosted DATETIME
);

insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (1, 'auctor gravida sem praesent id massa id', 'Chery Crowe', 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', '02/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (2, 'consequat dui nec nisi volutpat eleifend donec ut', 'Mill Minchell', 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', '04/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (3, 'parturient montes nascetur ridiculus mus vivamus vestibulum', 'Ellen Gomez', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit', '31/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (4, 'ut blandit non interdum', 'Lincoln Le Maitre', 'quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', '01/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (5, 'convallis eget eleifend luctus ultricies eu', 'Quinta Olivera', 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet', '30/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (6, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit', 'Worthy Chritchlow', 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac', '26/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (7, 'primis in faucibus', 'Jenelle Magson', 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel', '27/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (8, 'phasellus in felis donec semper sapien a', 'Juan Scandrite', 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', '31/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (9, 'ultrices posuere cubilia curae mauris viverra diam', 'Deidre Blenkinsop', 'in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet', '25/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (10, 'at velit eu est congue elementum', 'Louisette Di Boldi', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', '30/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (11, 'a ipsum integer a nibh', 'Bertrando Dryburgh', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit', '27/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (12, 'facilisi cras non velit nec nisi vulputate nonummy', 'Joyce Rowcastle', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et', '26/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (13, 'ac nibh fusce lacus purus aliquet at', 'Florina Dablin', 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non', '02/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (14, 'tristique in tempus sit amet sem fusce', 'Filippa Kisby', 'non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', '02/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (15, 'neque aenean auctor gravida', 'Sonny Dicty', 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis', '04/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (16, 'magna at nunc commodo placerat praesent blandit', 'Neile Jaggers', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient', '29/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (17, 'a libero nam dui proin leo odio porttitor id consequat', 'Agatha Hallewell', 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis', '04/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (18, 'sapien varius ut blandit non interdum in', 'Stuart Lodeke', 'erat eros viverra eget congue eget semper rutrum nulla nunc', '01/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (19, 'in sagittis dui vel nisl', 'Byrle Robjents', 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', '27/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (20, 'etiam vel augue vestibulum rutrum rutrum neque aenean', 'Lynn Lawless', 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', '02/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (21, 'dolor sit amet consectetuer adipiscing elit proin', 'Terrel Wheowall', 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus', '29/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (22, 'eget eros elementum pellentesque quisque porta volutpat erat quisque erat', 'Annabel Botterill', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing', '27/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (23, 'consequat ut nulla sed accumsan felis ut at dolor quis', 'Kendall Liston', 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', '01/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (24, 'arcu sed augue aliquam erat volutpat in congue', 'Willetta Livick', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed', '27/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (25, 'elit ac nulla sed vel enim', 'Samaria Worsnap', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu', '01/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (26, 'sapien quis libero', 'Layney Halfpenny', 'libero rutrum ac lobortis vel dapibus at diam nam tristique', '02/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (27, 'duis ac nibh fusce lacus', 'Lexie Dupre', 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus', '03/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (28, 'platea dictumst etiam faucibus cursus', 'Cody Legerwood', 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', '26/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (29, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor', 'Manny Logg', 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam', '01/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (30, 'vitae quam suspendisse potenti nullam porttitor lacus', 'Sanders Alvin', 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', '1/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (31, 'scelerisque mauris sit amet eros suspendisse accumsan', 'Conway Aveling', 'turpis enim blandit mi in porttitor pede justo eu massa donec', '01/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (32, 'cras mi pede', 'Annadiane Andrusyak', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu', '03/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (33, 'quam sapien varius ut blandit non interdum in ante vestibulum', 'Gussie Molloy', 'congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a', '29/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (34, 'accumsan felis ut at dolor quis odio consequat', 'Esma Garber', 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium', '01/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (35, 'congue etiam justo', 'Casar Hellier', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo', '28/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (36, 'tristique tortor eu', 'Debi Salvadore', 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', '27/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (37, 'luctus tincidunt nulla mollis molestie lorem quisque ut erat', 'Idelle Pawley', 'suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', '26/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (38, 'et commodo vulputate', 'Rena Waberer', 'pede ullamcorper augue a suscipit nulla elit ac nulla sed', '04/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (39, 'cursus urna ut tellus nulla ut erat id mauris vulputate', 'Rina Shoulder', 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit', '31/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (40, 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue', 'Emmey Warratt', 'pede libero quis orci nullam molestie nibh in lectus pellentesque at', '02/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (41, 'curabitur gravida nisi', 'Alasteir Elcombe', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', '27/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (42, 'risus praesent lectus vestibulum quam sapien varius ut blandit non', 'Pepi Rainton', 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat', '29/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (43, 'luctus et ultrices posuere cubilia curae', 'Fielding Tale', 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu', '28/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (44, 'interdum mauris ullamcorper purus sit amet nulla quisque', 'Karlik Mabey', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', '04/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (45, 'non mattis pulvinar', 'Rachael Billie', 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue', '02/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (46, 'nulla integer pede justo lacinia', 'Barnebas Ellison', 'nulla elit ac nulla sed vel enim sit amet nunc', '25/9/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (47, 'sapien sapien non mi integer ac neque duis bibendum', 'Lottie Reuss', 'mi nulla ac enim in tempor turpis nec euismod scelerisque', '29/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (48, 'nulla elit ac nulla sed vel enim sit amet', 'Iosep Orpen', 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula', '27/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (49, 'eu felis fusce', 'Valentia Penkman', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', '25/8/2019');
insert into Posts (PostID, PostTitle, Username, PostContent, DatePosted) values (50, 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 'Verna Woodfield', 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', '29/8/2019');